// Mocks generated by Mockito 5.4.6 from annotations
// in diabits_mobile/test/ui/health_connect/permission_gate_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i8;

import 'package:diabits_mobile/data/health_connect/permission_handler.dart'
    as _i3;
import 'package:diabits_mobile/data/manual_input/manual_input_repository.dart'
    as _i9;
import 'package:diabits_mobile/data/network/requests/login_request.dart' as _i7;
import 'package:diabits_mobile/data/network/requests/manual_input_request.dart'
    as _i11;
import 'package:diabits_mobile/data/network/requests/register_request.dart'
    as _i6;
import 'package:diabits_mobile/data/network/responses/manual_input_response.dart'
    as _i10;
import 'package:diabits_mobile/domain/auth/auth_state_manager.dart' as _i5;
import 'package:health/health.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHealth_0 extends _i1.SmartFake implements _i2.Health {
  _FakeHealth_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PermissionHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionHandler extends _i1.Mock implements _i3.PermissionHandler {
  MockPermissionHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Health> initHealthConnect() =>
      (super.noSuchMethod(
            Invocation.method(#initHealthConnect, []),
            returnValue: _i4.Future<_i2.Health>.value(
              _FakeHealth_0(this, Invocation.method(#initHealthConnect, [])),
            ),
          )
          as _i4.Future<_i2.Health>);
}

/// A class which mocks [AuthStateManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStateManager extends _i1.Mock implements _i5.AuthStateManager {
  MockAuthStateManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i5.AuthState.none,
          )
          as _i5.AuthState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<String?> register(_i6.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> login(_i7.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ManualInputRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockManualInputRepository extends _i1.Mock
    implements _i9.ManualInputRepository {
  MockManualInputRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i10.ManualInputResponse?> getManualInputForDay(DateTime? day) =>
      (super.noSuchMethod(
            Invocation.method(#getManualInputForDay, [day]),
            returnValue: _i4.Future<_i10.ManualInputResponse?>.value(),
          )
          as _i4.Future<_i10.ManualInputResponse?>);

  @override
  _i4.Future<bool> submitManualInputs(_i11.ManualInputRequest? req) =>
      (super.noSuchMethod(
            Invocation.method(#submitManualInputs, [req]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateManualInputs(_i11.ManualInputRequest? req) =>
      (super.noSuchMethod(
            Invocation.method(#updateManualInputs, [req]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteManualInputs(_i11.ManualInputDeleteRequest? req) =>
      (super.noSuchMethod(
            Invocation.method(#deleteManualInputs, [req]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
