// Mocks generated by Mockito 5.4.6 from annotations
// in diabits_mobile/test/data/health_connect/health_connect_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:diabits_mobile/data/health_connect/permission_handler.dart'
    as _i6;
import 'package:diabits_mobile/data/network/api_client.dart' as _i4;
import 'package:diabits_mobile/data/network/dtos/api_result.dart' as _i2;
import 'package:health/health.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0 extends _i1.SmartFake implements _i2.ApiResult {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealth_1 extends _i1.SmartFake implements _i3.Health {
  _FakeHealth_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ApiResult> get(String? path, {Map<String, String>? params}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [path], {#params: params}),
            returnValue: _i5.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(
                this,
                Invocation.method(#get, [path], {#params: params}),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult>);

  @override
  _i5.Future<_i2.ApiResult> post(
    String? path,
    Object? body, {
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path, body], {#timeout: timeout}),
            returnValue: _i5.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(
                this,
                Invocation.method(#post, [path, body], {#timeout: timeout}),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult>);

  @override
  _i5.Future<_i2.ApiResult> put(String? path, Object? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path, body]),
            returnValue: _i5.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(this, Invocation.method(#put, [path, body])),
            ),
          )
          as _i5.Future<_i2.ApiResult>);

  @override
  _i5.Future<_i2.ApiResult> delete(String? path, {Object? body}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#body: body}),
            returnValue: _i5.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(
                this,
                Invocation.method(#delete, [path], {#body: body}),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PermissionHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionHandler extends _i1.Mock implements _i6.PermissionHandler {
  MockPermissionHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Health> initHealthConnect() =>
      (super.noSuchMethod(
            Invocation.method(#initHealthConnect, []),
            returnValue: _i5.Future<_i3.Health>.value(
              _FakeHealth_1(this, Invocation.method(#initHealthConnect, [])),
            ),
          )
          as _i5.Future<_i3.Health>);
}

/// A class which mocks [Health].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealth extends _i1.Mock implements _i3.Health {
  MockHealth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HealthConnectSdkStatus get healthConnectSdkStatus =>
      (super.noSuchMethod(
            Invocation.getter(#healthConnectSdkStatus),
            returnValue: _i3.HealthConnectSdkStatus.sdkUnavailable,
          )
          as _i3.HealthConnectSdkStatus);

  @override
  _i3.HealthPlatformType get platformType =>
      (super.noSuchMethod(
            Invocation.getter(#platformType),
            returnValue: _i3.HealthPlatformType.appleHealth,
          )
          as _i3.HealthPlatformType);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  _i5.Future<void> configure() =>
      (super.noSuchMethod(
            Invocation.method(#configure, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isDataTypeAvailable(_i3.HealthDataType? dataType) =>
      (super.noSuchMethod(
            Invocation.method(#isDataTypeAvailable, [dataType]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<bool?> hasPermissions(
    List<_i3.HealthDataType>? types, {
    List<_i3.HealthDataAccess>? permissions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasPermissions,
              [types],
              {#permissions: permissions},
            ),
            returnValue: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);

  @override
  _i5.Future<void> revokePermissions() =>
      (super.noSuchMethod(
            Invocation.method(#revokePermissions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.HealthConnectSdkStatus?> getHealthConnectSdkStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthConnectSdkStatus, []),
            returnValue: _i5.Future<_i3.HealthConnectSdkStatus?>.value(),
          )
          as _i5.Future<_i3.HealthConnectSdkStatus?>);

  @override
  _i5.Future<bool> isHealthConnectAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isHealthConnectAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> installHealthConnect() =>
      (super.noSuchMethod(
            Invocation.method(#installHealthConnect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isHealthDataHistoryAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isHealthDataHistoryAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isHealthDataHistoryAuthorized() =>
      (super.noSuchMethod(
            Invocation.method(#isHealthDataHistoryAuthorized, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestHealthDataHistoryAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#requestHealthDataHistoryAuthorization, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isHealthDataInBackgroundAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isHealthDataInBackgroundAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isHealthDataInBackgroundAuthorized() =>
      (super.noSuchMethod(
            Invocation.method(#isHealthDataInBackgroundAuthorized, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestHealthDataInBackgroundAuthorization() =>
      (super.noSuchMethod(
            Invocation.method(#requestHealthDataInBackgroundAuthorization, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isSkinTemperatureAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isSkinTemperatureAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestAuthorization(
    List<_i3.HealthDataType>? types, {
    List<_i3.HealthDataAccess>? permissions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestAuthorization,
              [types],
              {#permissions: permissions},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeHealthData({
    required double? value,
    _i3.HealthDataUnit? unit,
    required _i3.HealthDataType? type,
    required DateTime? startTime,
    String? clientRecordId,
    double? clientRecordVersion,
    DateTime? endTime,
    _i3.RecordingMethod? recordingMethod = _i3.RecordingMethod.automatic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeHealthData, [], {
              #value: value,
              #unit: unit,
              #type: type,
              #startTime: startTime,
              #clientRecordId: clientRecordId,
              #clientRecordVersion: clientRecordVersion,
              #endTime: endTime,
              #recordingMethod: recordingMethod,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeActivityIntensity({
    required _i3.ActivityIntensityLevel? intensityLevel,
    required DateTime? startTime,
    DateTime? endTime,
    _i3.RecordingMethod? recordingMethod = _i3.RecordingMethod.automatic,
    String? clientRecordId,
    double? clientRecordVersion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeActivityIntensity, [], {
              #intensityLevel: intensityLevel,
              #startTime: startTime,
              #endTime: endTime,
              #recordingMethod: recordingMethod,
              #clientRecordId: clientRecordId,
              #clientRecordVersion: clientRecordVersion,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> delete({
    required _i3.HealthDataType? type,
    required DateTime? startTime,
    DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #type: type,
              #startTime: startTime,
              #endTime: endTime,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteByUUID({
    required String? uuid,
    _i3.HealthDataType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteByUUID, [], {#uuid: uuid, #type: type}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteByClientRecordId({
    required _i3.HealthDataType? dataTypeKey,
    required String? clientRecordId,
    String? recordId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteByClientRecordId, [], {
              #dataTypeKey: dataTypeKey,
              #clientRecordId: clientRecordId,
              #recordId: recordId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeBloodPressure({
    required int? systolic,
    required int? diastolic,
    required DateTime? startTime,
    String? clientRecordId,
    double? clientRecordVersion,
    DateTime? endTime,
    _i3.RecordingMethod? recordingMethod = _i3.RecordingMethod.automatic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeBloodPressure, [], {
              #systolic: systolic,
              #diastolic: diastolic,
              #startTime: startTime,
              #clientRecordId: clientRecordId,
              #clientRecordVersion: clientRecordVersion,
              #endTime: endTime,
              #recordingMethod: recordingMethod,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeBloodOxygen({
    required double? saturation,
    required DateTime? startTime,
    DateTime? endTime,
    _i3.RecordingMethod? recordingMethod = _i3.RecordingMethod.automatic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeBloodOxygen, [], {
              #saturation: saturation,
              #startTime: startTime,
              #endTime: endTime,
              #recordingMethod: recordingMethod,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeMeal({
    required _i3.MealType? mealType,
    required DateTime? startTime,
    required DateTime? endTime,
    String? clientRecordId,
    double? clientRecordVersion,
    double? caloriesConsumed,
    double? carbohydrates,
    double? protein,
    double? fatTotal,
    String? name,
    double? caffeine,
    double? vitaminA,
    double? b1Thiamin,
    double? b2Riboflavin,
    double? b3Niacin,
    double? b5PantothenicAcid,
    double? b6Pyridoxine,
    double? b7Biotin,
    double? b9Folate,
    double? b12Cobalamin,
    double? vitaminC,
    double? vitaminD,
    double? vitaminE,
    double? vitaminK,
    double? calcium,
    double? cholesterol,
    double? chloride,
    double? chromium,
    double? copper,
    double? fatUnsaturated,
    double? fatMonounsaturated,
    double? fatPolyunsaturated,
    double? fatSaturated,
    double? fatTransMonoenoic,
    double? fiber,
    double? iodine,
    double? iron,
    double? magnesium,
    double? manganese,
    double? molybdenum,
    double? phosphorus,
    double? potassium,
    double? selenium,
    double? sodium,
    double? sugar,
    double? water,
    double? zinc,
    _i3.RecordingMethod? recordingMethod = _i3.RecordingMethod.automatic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeMeal, [], {
              #mealType: mealType,
              #startTime: startTime,
              #endTime: endTime,
              #clientRecordId: clientRecordId,
              #clientRecordVersion: clientRecordVersion,
              #caloriesConsumed: caloriesConsumed,
              #carbohydrates: carbohydrates,
              #protein: protein,
              #fatTotal: fatTotal,
              #name: name,
              #caffeine: caffeine,
              #vitaminA: vitaminA,
              #b1Thiamin: b1Thiamin,
              #b2Riboflavin: b2Riboflavin,
              #b3Niacin: b3Niacin,
              #b5PantothenicAcid: b5PantothenicAcid,
              #b6Pyridoxine: b6Pyridoxine,
              #b7Biotin: b7Biotin,
              #b9Folate: b9Folate,
              #b12Cobalamin: b12Cobalamin,
              #vitaminC: vitaminC,
              #vitaminD: vitaminD,
              #vitaminE: vitaminE,
              #vitaminK: vitaminK,
              #calcium: calcium,
              #cholesterol: cholesterol,
              #chloride: chloride,
              #chromium: chromium,
              #copper: copper,
              #fatUnsaturated: fatUnsaturated,
              #fatMonounsaturated: fatMonounsaturated,
              #fatPolyunsaturated: fatPolyunsaturated,
              #fatSaturated: fatSaturated,
              #fatTransMonoenoic: fatTransMonoenoic,
              #fiber: fiber,
              #iodine: iodine,
              #iron: iron,
              #magnesium: magnesium,
              #manganese: manganese,
              #molybdenum: molybdenum,
              #phosphorus: phosphorus,
              #potassium: potassium,
              #selenium: selenium,
              #sodium: sodium,
              #sugar: sugar,
              #water: water,
              #zinc: zinc,
              #recordingMethod: recordingMethod,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeMenstruationFlow({
    required _i3.MenstrualFlow? flow,
    required DateTime? startTime,
    required DateTime? endTime,
    required bool? isStartOfCycle,
    _i3.RecordingMethod? recordingMethod = _i3.RecordingMethod.automatic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeMenstruationFlow, [], {
              #flow: flow,
              #startTime: startTime,
              #endTime: endTime,
              #isStartOfCycle: isStartOfCycle,
              #recordingMethod: recordingMethod,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeAudiogram({
    required List<double>? frequencies,
    required List<double>? leftEarSensitivities,
    required List<double>? rightEarSensitivities,
    required DateTime? startTime,
    DateTime? endTime,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeAudiogram, [], {
              #frequencies: frequencies,
              #leftEarSensitivities: leftEarSensitivities,
              #rightEarSensitivities: rightEarSensitivities,
              #startTime: startTime,
              #endTime: endTime,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> writeInsulinDelivery(
    double? units,
    _i3.InsulinDeliveryReason? reason,
    DateTime? startTime,
    DateTime? endTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeInsulinDelivery, [
              units,
              reason,
              startTime,
              endTime,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.HealthDataPoint?> getHealthDataByUUID({
    required String? uuid,
    required _i3.HealthDataType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHealthDataByUUID, [], {
              #uuid: uuid,
              #type: type,
            }),
            returnValue: _i5.Future<_i3.HealthDataPoint?>.value(),
          )
          as _i5.Future<_i3.HealthDataPoint?>);

  @override
  _i5.Future<List<_i3.HealthDataPoint>> getHealthDataFromTypes({
    required List<_i3.HealthDataType>? types,
    Map<_i3.HealthDataType, _i3.HealthDataUnit>? preferredUnits,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i3.RecordingMethod>? recordingMethodsToFilter = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHealthDataFromTypes, [], {
              #types: types,
              #preferredUnits: preferredUnits,
              #startTime: startTime,
              #endTime: endTime,
              #recordingMethodsToFilter: recordingMethodsToFilter,
            }),
            returnValue: _i5.Future<List<_i3.HealthDataPoint>>.value(
              <_i3.HealthDataPoint>[],
            ),
          )
          as _i5.Future<List<_i3.HealthDataPoint>>);

  @override
  _i5.Future<List<_i3.HealthDataPoint>> getHealthIntervalDataFromTypes({
    required DateTime? startDate,
    required DateTime? endDate,
    required List<_i3.HealthDataType>? types,
    required int? interval,
    List<_i3.RecordingMethod>? recordingMethodsToFilter = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHealthIntervalDataFromTypes, [], {
              #startDate: startDate,
              #endDate: endDate,
              #types: types,
              #interval: interval,
              #recordingMethodsToFilter: recordingMethodsToFilter,
            }),
            returnValue: _i5.Future<List<_i3.HealthDataPoint>>.value(
              <_i3.HealthDataPoint>[],
            ),
          )
          as _i5.Future<List<_i3.HealthDataPoint>>);

  @override
  _i5.Future<List<_i3.HealthDataPoint>> getHealthAggregateDataFromTypes({
    required List<_i3.HealthDataType>? types,
    required DateTime? startDate,
    required DateTime? endDate,
    int? activitySegmentDuration = 1,
    bool? includeManualEntry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHealthAggregateDataFromTypes, [], {
              #types: types,
              #startDate: startDate,
              #endDate: endDate,
              #activitySegmentDuration: activitySegmentDuration,
              #includeManualEntry: includeManualEntry,
            }),
            returnValue: _i5.Future<List<_i3.HealthDataPoint>>.value(
              <_i3.HealthDataPoint>[],
            ),
          )
          as _i5.Future<List<_i3.HealthDataPoint>>);

  @override
  _i5.Future<String?> getChangesToken({
    required List<_i3.HealthDataType>? types,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChangesToken, [], {#types: types}),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i3.HealthChangesResponse?> getChanges({
    required String? changesToken,
    bool? includeSelf = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChanges, [], {
              #changesToken: changesToken,
              #includeSelf: includeSelf,
            }),
            returnValue: _i5.Future<_i3.HealthChangesResponse?>.value(),
          )
          as _i5.Future<_i3.HealthChangesResponse?>);

  @override
  List<_i3.HealthDataPoint> removeDuplicates(
    List<_i3.HealthDataPoint>? points,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeDuplicates, [points]),
            returnValue: <_i3.HealthDataPoint>[],
          )
          as List<_i3.HealthDataPoint>);

  @override
  _i5.Future<int?> getTotalStepsInInterval(
    DateTime? startTime,
    DateTime? endTime, {
    bool? includeManualEntry = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTotalStepsInInterval,
              [startTime, endTime],
              {#includeManualEntry: includeManualEntry},
            ),
            returnValue: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<bool> writeWorkoutData({
    required _i3.HealthWorkoutActivityType? activityType,
    required DateTime? start,
    required DateTime? end,
    int? totalEnergyBurned,
    _i3.HealthDataUnit? totalEnergyBurnedUnit = _i3.HealthDataUnit.KILOCALORIE,
    int? totalDistance,
    _i3.HealthDataUnit? totalDistanceUnit = _i3.HealthDataUnit.METER,
    String? title,
    _i3.RecordingMethod? recordingMethod = _i3.RecordingMethod.automatic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeWorkoutData, [], {
              #activityType: activityType,
              #start: start,
              #end: end,
              #totalEnergyBurned: totalEnergyBurned,
              #totalEnergyBurnedUnit: totalEnergyBurnedUnit,
              #totalDistance: totalDistance,
              #totalDistanceUnit: totalDistanceUnit,
              #title: title,
              #recordingMethod: recordingMethod,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> startWorkoutRoute() =>
      (super.noSuchMethod(
            Invocation.method(#startWorkoutRoute, []),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#startWorkoutRoute, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> insertWorkoutRouteData({
    required String? builderId,
    required List<_i3.WorkoutRouteLocation>? locations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertWorkoutRouteData, [], {
              #builderId: builderId,
              #locations: locations,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> finishWorkoutRoute({
    required String? builderId,
    required String? workoutUuid,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishWorkoutRoute, [], {
              #builderId: builderId,
              #workoutUuid: workoutUuid,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#finishWorkoutRoute, [], {
                  #builderId: builderId,
                  #workoutUuid: workoutUuid,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> discardWorkoutRoute(String? builderId) =>
      (super.noSuchMethod(
            Invocation.method(#discardWorkoutRoute, [builderId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
