// Mocks generated by Mockito 5.4.6 from annotations
// in diabits_mobile/test/data/auth/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:diabits_mobile/data/auth/token_storage.dart' as _i5;
import 'package:diabits_mobile/data/network/api_client.dart' as _i3;
import 'package:diabits_mobile/data/network/dtos/api_result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0 extends _i1.SmartFake implements _i2.ApiResult {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult> get(String? path, {Map<String, String>? params}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [path], {#params: params}),
            returnValue: _i4.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(
                this,
                Invocation.method(#get, [path], {#params: params}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult>);

  @override
  _i4.Future<_i2.ApiResult> post(
    String? path,
    Object? body, {
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path, body], {#timeout: timeout}),
            returnValue: _i4.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(
                this,
                Invocation.method(#post, [path, body], {#timeout: timeout}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult>);

  @override
  _i4.Future<_i2.ApiResult> put(String? path, Object? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path, body]),
            returnValue: _i4.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(this, Invocation.method(#put, [path, body])),
            ),
          )
          as _i4.Future<_i2.ApiResult>);

  @override
  _i4.Future<_i2.ApiResult> delete(String? path, {Object? body}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#body: body}),
            returnValue: _i4.Future<_i2.ApiResult>.value(
              _FakeApiResult_0(
                this,
                Invocation.method(#delete, [path], {#body: body}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i5.TokenStorage {
  MockTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
