// Mocks generated by Mockito 5.4.6 from annotations
// in diabits_mobile/test/domain/auth/auth_state_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:diabits_mobile/data/auth/auth_repository.dart' as _i3;
import 'package:diabits_mobile/data/auth/dtos/auth_result.dart' as _i2;
import 'package:diabits_mobile/data/health_connect/sync_scheduler.dart' as _i8;
import 'package:diabits_mobile/data/network/requests/login_request.dart' as _i6;
import 'package:diabits_mobile/data/network/requests/register_request.dart'
    as _i5;
import 'package:diabits_mobile/domain/auth/auth_state_manager.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthResult> register(_i5.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(this, Invocation.method(#register, [request])),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> login(_i6.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.AuthState?> autoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#autoLogin, []),
            returnValue: _i4.Future<_i7.AuthState?>.value(),
          )
          as _i4.Future<_i7.AuthState?>);

  @override
  _i4.Future<bool> hasTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasTokens, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [SyncScheduler].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncScheduler extends _i1.Mock implements _i8.SyncScheduler {
  MockSyncScheduler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> startBackgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#startBackgroundSync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopBackgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#stopBackgroundSync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
